
services:
  
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy-hotel
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - auth-microservice
      - habitacion_service
      - reservas-microservice
    networks:
      - app-network
    restart: always

  
  auth-microservice:
    build:
      context: ./auth-nodejs/
      dockerfile: Dockerfile
    container_name: auth-service_2
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db-auth
      DB_NAME: db_users_auth
      DB_USER: auth_user
      DB_PASS: auth_password
      JWT_SECRET: EstaEsUnaClaveMuySeguraDeAlMenos32Bytes!
    depends_on:
      db-auth:
        condition: service_healthy
    networks:
      - app-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/auth/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  
  db-auth:
    image: mysql:8.0
    container_name: auth-mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: db_users_auth
      MYSQL_USER: auth_user
      MYSQL_PASSWORD: auth_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3308:3306"
    volumes:
      - auth_data:/var/lib/mysql
    networks:
      - app-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  
  mongo:
    image: mongo:7.0
    container_name: mongo_habitaciones
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  habitacion_service:
    image: efr4/habitacion_service
    container_name: habitacion_service
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - MongoDB__ConnectionString=mongodb://mongo:27017
      - MongoDB__Database=habitacionesdb
      - MongoDB__HabitacionesCollection=habitaciones
      - Jwt__Key=EstaEsUnaClaveMuySeguraDeAlMenos32Bytes!
    depends_on:
      - mongo
    networks:
      - app-network


  reservas-microservice:
    build:
      context: ./reservas-nodejs/
      dockerfile: Dockerfile
    container_name: reservas-service
    restart: always
    environment:
      DB_HOST: db-reservas
      DB_NAME: reservas_db
      DB_USER: reservas_user
      DB_PASS: reservas_password
      JWT_SECRET: EstaEsUnaClaveMuySeguraDeAlMenos32Bytes!
    ports:
      - "4000:4000"
    depends_on:
      - db-reservas
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  
  db-reservas:
    image: mysql:8.0
    container_name: reservas-mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: reservas_db
      MYSQL_USER: reservas_user
      MYSQL_PASSWORD: reservas_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3307:3306"
    volumes:
      - reservas_data:/var/lib/mysql
      - ./reservas-nodejs/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

networks:
  app-network:
    driver: bridge

volumes:
  auth_data:
  mongo_data:
  reservas_data: