services:
  auth-service:
    build: .
    container_name: auth-service
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      API_PORT: 8080
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db
    networks:
      - auth-network
    volumes:
      - ./.env:/app/.env

  db:
    image: mysql:8
    container_name: auth-mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge

volumes:
  mysql-data:
