version: '3.8'

services:
  clientes:
    build:
      context: ./clientes
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_NAME=db_sistema_ventas_microservices
      - DB_USER=root
      - DB_PASS=
    depends_on:
      - db

  producto:
    build:
      context: ./producto
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - DB_HOST=db
      - DB_NAME=db_sistema_ventas_microservices
      - DB_USER=root
      - DB_PASS=
    depends_on:
      - db

  factura:
    build:
      context: ./factura
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=db
      - DB_NAME=db_sistema_ventas_microservices
      - DB_USER=root
      - DB_PASS=
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: db_sistema_ventas_microservices
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: